
# 测试环境
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://${ip}:3306/zdjy?useUnicode=true&characterEncoding=utf8&useSSL=false&&useJDBCCompliantTimezoneShift=true&&useLegacyDatetimeCode=false&&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: zdjy
    password: zdjy
  redis:
    host: ${ip}
    port: 6380
    password: zdjy

logging:
  config: classpath:log4j2-test.xml

ip: 123.56.142.84
#ip: 192.168.0.2
studyUrl: https://test.shell.yydz100.com
adminDomin: http://test.admin.yydz100.com/dept

cross:
  url: http://192.168.0.*:5000

quartz:
  port: 8083

# 公众号配置信息
gongzhonghao:
  appId: wx876660e0c4b48729
  secret: 99c6d530ec67582061c731b43e6a2448
  redirect:
    # 微信授权结束后跳转的路径
    partner: ${studyUrl}/partner

qywx:
  appId: wwe6e0ef9e01f6d6aa
  secret: pxf5D_K3F9jFPwRTksCRXERkar3rOdOLmyYfImmv11o
  redirect:
    # 企业微信登录地址
    login: ${studyUrl}/qy/login
