
# 测试环境
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://${ip}:3306/zdjy?useUnicode=true&characterEncoding=utf8&useSSL=false&&useJDBCCompliantTimezoneShift=true&&useLegacyDatetimeCode=false&&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: zdjy
    password: zdjy
  redis:
    host: ${ip}
    port: 6380
    password: zdjy
  cloud:
    nacos:
      discovery:
        server-addr: nacos.duizhang100.cn:8848
        namespace: a8dd697b-5d6d-4844-bcc7-54a7732644e8
  application:
    name: server1

logging:
  config: classpath:log4j2-test.xml

ip: 123.56.142.84
#ip: 192.168.0.2
studyUrl: https://test.shell.yydz100.com
adminDomin: http://test.admin.yydz100.com/dept

quartz:
  port: 8083

# 公众号配置信息
gongzhonghao:
  appId: wx876660e0c4b48729
  secret: 99c6d530ec67582061c731b43e6a2448
  redirect:
    # 微信授权结束后跳转的路径
    partner: ${studyUrl}/partner

qywx:
  appId: wwe6e0ef9e01f6d6aa
  secret: pxf5D_K3F9jFPwRTksCRXERkar3rOdOLmyYfImmv11o
  # 授权链接
  authLink: https://open.weixin.qq.com/connect/oauth2/authorize?appid=${qywx.appId}&redirect_uri=${qywx.redirect.redirect_uri}&response_type=code&scope=snsapi_base&state=STATE#wechat_redirect
  redirect:
    # 企业微信登录地址
    login: ${studyUrl}/qy/login
    # 授权后重定向的回调链接地址
    redirect_uri: ${studyUrl}/ec/qy/authgetUserInfo
