
# 测试环境
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://${ip}:3306/zdjy?useUnicode=true&characterEncoding=utf8&useSSL=false&&useJDBCCompliantTimezoneShift=true&&useLegacyDatetimeCode=false&&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: zdjy
    password: zdjy
  redis:
    host: ${ip}
    port: 6380
    password: zdjy

logging:
  config: classpath:logback-test.xml

ip: 123.56.142.84
#ip: 192.168.0.2
studyUrl: https://test.shell.yydz100.com
adminDomin: http://test.admin.yydz100.com/dept

cross:
  url: http://192.168.0.*:5000

quartz:
  port: 8083

# 公众号配置信息
gongzhonghao:
  appId: wx991c0b0330281fd1
  secret: e512f4eae621183834ba2376a63eaa8e
  redirect:
    # 微信授权结束后跳转到合伙人测试页面的路径
    partner: ${studyUrl}/partner
