ip: 39.106.181.151
spring:
  profiles: prd
  servlet:
    multipart:
      file-size-threshold: 15MB
  datasource:
    url: jdbc:mysql://localhost:3306/zdjy?useUnicode=true&characterEncoding=utf8&useSSL=false&&useJDBCCompliantTimezoneShift=true&&useLegacyDatetimeCode=false&&serverTimezone=Asia/Shanghai
    username: root
    password: zhide8800
  redis:
    host: ${ip}
    port: 6379
    password: zhide2018
  cloud:
    nacos:
      discovery:
        server-addr: nacos.duizhang100.cn:8848
        namespace: 98b133ab-9b67-4919-adb4-e8a1c96db7cf
  application:
    name: server1
  zipkin:
    base-url: http://${ip}:9411/
    discoveryClientEnabled: false
  sleuth:
    sampler:
      # 抽样率，默认是0.1（10%）
      probability: 0.1
feign:
  client:
    config:
      # 通过 default 进行全局配置
      default:
#        loggerLevel: error
        connectTimeout: 10000
        readTimeout: 10000

server:
  port: 9082
  tomcat:
    max-threads: 512
    min-spare-threads: 20
    max-connections: 512
logging:
  config: classpath:log4j2-prd.xml

studyUrl: https://www.yydz100.com
adminDomin: https://admin.duizhang100.cn/dept

# 需要执行定时任务的服务器ip和端口
quartz:
  ip: ${ip}
  port: 9082

# sentinel配置
ahas:
  namespace: prd
  license: 05a8f00991ce4f36b8b7596c469ff105
project:
  name: yydz-prd

# 公众号配置信息
gongzhonghao:
  appId: wx876660e0c4b48729
  secret: 99c6d530ec67582061c731b43e6a2448
  redirect:
    # 微信授权结束后跳转的路径
    partner: ${studyUrl}/partner
qywx:
  appId: wwe6e0ef9e01f6d6aa
  secret: pxf5D_K3F9jFPwRTksCRXERkar3rOdOLmyYfImmv11o
  # 授权链接
  authLink: https://open.weixin.qq.com/connect/oauth2/authorize?appid=${qywx.appId}&redirect_uri=${qywx.redirect.redirect_uri}&response_type=code&scope=snsapi_base&state=STATE#wechat_redirect
  redirect:
    # 企业微信登录地址
    login: ${studyUrl}/qy/login
    # 授权后重定向的回调链接地址
    redirect_uri: ${studyUrl}/ec/qy/authgetUserInfo

