spring:
  profiles:
    active: dev
  http:
    encoding:
      force: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Chongqing
  datasource:
    druid:
      # 初始化时建立物理连接的个
      initial-size: 5
      # 最大连接池数量
      max-active: 1000
      # 最小连接池数量
      min-idle: 100
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-time-millis: 300000
      # 用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: SELECT 1 FROM DUAL
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: false
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      max-pool-prepared-statement-per-connection-size: 50
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
  main:
    allow-bean-definition-overriding: true
  # 邮箱服务器地址
  mail:
    host: smtp.163.com
    port: 465
    # 用户名
    username: duofenduizhang@163.com
    # 密码
    password: GYPEORBAFFDLKQYW
    # 编码
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
          starttls:
            enable: true
  mvc:
    servlet:
      load-on-startup: 1
  servlet:
    multipart:
      max-file-size: 15MB
# 发送者邮箱
mail:
  fromMail:
    addr: duofenduizhang@163.com
management:
  endpoints:
    web:
      exposure:
        include: '*'
feign:
  client:
    config:
      # 通过 default 进行全局配置
      default:
        loggerLevel: full
        connectTimeout: 5000
        readTimeout: 5000
server:
  tomcat:
    uri-encoding: utf-8
    connection-timeout: 30m
  servlet:
    session:
      timeout: 30m
mybatis:
  type-aliases-package: com.zhidejiaoyu.common.pojo

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

baidu: https://fanyi.baidu.com/gettts?lan=en&spd=3&source=web&text=

# ip location，IP定位，距离计算
# 腾讯地图，接口地址：https://lbs.qq.com/webservice_v1/guide-gcoder.html
tencent:
  map:
    key: UGPBZ-SVC6X-O3W43-TYLAQ-CVERH-OFF65
    url: https://apis.map.qq.com/ws/geocoder/v1/
  # 腾讯距离计算，接口地址：https://lbs.qq.com/webservice_v1/guide-distance.html
  distance:
    url: https://apis.map.qq.com/ws/distance/v1/
  # 腾讯 ip 定位
  location:
    url: https://apis.map.qq.com/ws/location/v1/ip

youdao:
  # youdao voice create
  create: https://dict.youdao.com/dictvoice?type=2&audio=
  # 有道翻译
  appKey: 22e4622be137dac9
  youdaoUrl: https://openapi.youdao.com/api
  md5Key: OsGxRcsnty1MGvnGEOPPRGM8DK2dAAka
  from: EN
  to: zh-CHS
