
# 预生产环境，业务人员测试使用
spring:
  profiles: pre-prd
  datasource:
    url: jdbc:mysql://${ip}:3306/zdjy?useUnicode=true&characterEncoding=utf8&useSSL=false&&useJDBCCompliantTimezoneShift=true&&useLegacyDatetimeCode=false&&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: zdjy
    password: zdjy
  redis:
    host: ${ip}
    port: 6380
    password: zdjy
  cloud:
    nacos:
      discovery:
        server-addr: nacos.duizhang100.cn:8848
        namespace: 5be896bc-65b4-4339-9559-ef90e569dcbf

  zipkin:
    base-url: http://${ip}:9411/
    discoveryClientEnabled: false
  sleuth:
    sampler:
      # 抽样率，默认是0.1（10%）
      probability: 1.0
logging:
  config: classpath:log4j2-test.xml

ip: 123.56.142.84
