
# 测试环境
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://${ip}:3306/zdjy?useUnicode=true&characterEncoding=utf8&useSSL=false&&useJDBCCompliantTimezoneShift=true&&useLegacyDatetimeCode=false&&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: zdjy
    password: zdjy
  redis:
    host: ${ip}
    port: 6380
    password: zdjy
  cloud:
    nacos:
      discovery:
        server-addr: nacos.duizhang100.cn:8848
        namespace: d622563f-9907-43e3-9d00-349c6468678e

  zipkin:
    base-url: http://${ip}:9411/
    discoveryClientEnabled: false
  sleuth:
    sampler:
      # 抽样率，默认是0.1（10%）
      probability: 1.0
logging:
  config: classpath:log4j2-test.xml

ip: 123.56.142.84
