ip: 39.106.181.151
spring:
  profiles: prd
  servlet:
    multipart:
      file-size-threshold: 15MB
  datasource:
    url: jdbc:mysql://localhost:3306/zdjy?useUnicode=true&characterEncoding=utf8&useSSL=false&&useJDBCCompliantTimezoneShift=true&&useLegacyDatetimeCode=false&&serverTimezone=Asia/Shanghai
    username: root
    password: zhide8800
    druid:
      # 初始化时建立物理连接的个
      initial-size: 5
      # 最大连接池数量
      max-active: 1000
      # 最小连接池数量
      min-idle: 100
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-time-millis: 300000
      # 用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: SELECT 1 FROM DUAL
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: false
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      max-pool-prepared-statement-per-connection-size: 50
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
  redis:
    host: ${ip}
    port: 6379
    password: zhide2018
  cloud:
    nacos:
      discovery:
        server-addr: nacos.duizhang100.cn:8848
        namespace: 98b133ab-9b67-4919-adb4-e8a1c96db7cf

  zipkin:
    base-url: http://${ip}:9411/
    discoveryClientEnabled: false
  sleuth:
    sampler:
      # 抽样率，默认是0.1（10%）
      probability: 0.1
feign:
  client:
    config:
      # 通过 default 进行全局配置
      default:
#        loggerLevel: error
        connectTimeout: 10000
        readTimeout: 10000

server:
  port: 9098
  tomcat:
    max-threads: 512
    min-spare-threads: 20
    max-connections: 512
logging:
  config: classpath:log4j2-prd.xml

# sentinel配置
ahas:
  namespace: prd
  license: 05a8f00991ce4f36b8b7596c469ff105
project:
  name: teacher-prd

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
