spring:
  application:
    name: course
  profiles:
    active: dev
  http:
    encoding:
      force: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Chongqing

server:
  tomcat:
    uri-encoding: utf-8
    connection-timeout: 30m
  servlet:
    session:
      timeout: 120m

mybatis:
  type-aliases-package: com.zhidejiaoyu.common.pojo

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
