spring:
  application:
    name: center
  profiles:
    active: dev
  http:
    encoding:
      force: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Chongqing
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-file-size: 15MB
server:
  servlet:
    context-path: /center
  tomcat:
    uri-encoding: utf-8
    connection-timeout: 30m
mybatis:
  type-aliases-package: com.zhidejiaoyu.common.pojo

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql

