ip: 39.106.181.151
spring:
  profiles: prd
  datasource:
    url: jdbc:mysql://localhost:3306/center?useUnicode=true&characterEncoding=utf8&useSSL=false&&useJDBCCompliantTimezoneShift=true&&useLegacyDatetimeCode=false&&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: zhide8800
    druid:
      # 初始化时建立物理连接的个
      initial-size: 5
      # 最大连接池数量
      max-active: 1000
      # 最小连接池数量
      min-idle: 100
      # 获取连接时最大等待时间，单位毫秒
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 连接保持空闲而不被驱逐的最小时间
      min-evictable-idle-time-millis: 300000
      # 用来检测连接是否有效的sql，要求是一个查询语句
      validation-query: SELECT 1 FROM DUAL
      # 建议配置为true，不影响性能，并且保证安全性。申请连接的时候检测，如果空闲时间大于timeBetweenEvictionRunsMillis，执行validationQuery检测连接是否有效。
      test-while-idle: true
      # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-borrow: false
      # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
      test-on-return: false
      # 是否缓存preparedStatement，也就是PSCache。PSCache对支持游标的数据库性能提升巨大，比如说oracle。在mysql下建议关闭。
      pool-prepared-statements: false
      # 要启用PSCache，必须配置大于0，当大于0时，poolPreparedStatements自动触发修改为true。
      max-pool-prepared-statement-per-connection-size: 50
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计
      filters: stat,wall
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=1000
      # 合并多个DruidDataSource的监控数据
      use-global-data-source-stat: true
  redis:
    host: ${ip}
    port: 6379
    password: zhide2018
  application:
    name: center
  cloud:
    nacos:
      discovery:
        server-addr: nacos.duizhang100.cn:8848
        namespace: 98b133ab-9b67-4919-adb4-e8a1c96db7cf
  zipkin:
    base-url: http://${ip}:9411/
    discoveryClientEnabled: false
  sleuth:
    sampler:
      # 抽样率，默认是0.1（10%）
      probability: 0.1
feign:
  client:
    config:
      # 通过 default 进行全局配置
      default:
#        logger-level: error
        connectTimeout: 10000
        readTimeout: 10000
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
server:
  port: 9100
  tomcat:
    max-connections: 512
    threads:
      min-spare: 20
      max: 512
logging:
  config: classpath:log4j2-prd.xml

# 公众号配置信息
studyUrl: https://centre.duizhang100.cn
gongzhonghao:
  appId: wx876660e0c4b48729
  secret: 99c6d530ec67582061c731b43e6a2448
  redirect:
    # 微信授权结束后跳转的路径
    partner: ${studyUrl}/partner
qywx:
  appId: ww50bff9461dc34208
  secret: DwNg4QieQYGQ9mJdu1wkV50z4YiHPpiH1gQ0TcKty4U
  # 授权链接
  authLink: https://open.weixin.qq.com/connect/oauth2/authorize?appid=${qywx.appId}&redirect_uri=${qywx.redirect.redirect_uri}&response_type=code&scope=snsapi_base&state=STATE#wechat_redirect
  redirect:
    # 企业微信登录地址
    login: ${studyUrl}/authorization
    # 授权后重定向的回调链接地址
    redirect_uri: ${studyUrl}/center/wechat/qy/auth/auth

management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
