ip: 123.56.142.84
# 预生产环境，业务人员测试使用
spring:
  profiles: pre-prd
  datasource:
    # 开发服务器
    url: jdbc:mysql://${ip}:3306/center?useUnicode=true&characterEncoding=utf8&useSSL=false&&useJDBCCompliantTimezoneShift=true&&useLegacyDatetimeCode=false&&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: zdjy
    password: zdjy
  redis:
    host: ${ip}
    port: 6380
    password: zdjy
  application:
    name: center
  cloud:
    nacos:
      discovery:
        server-addr: nacos.duizhang100.cn:8848
        namespace: 5be896bc-65b4-4339-9559-ef90e569dcbf
  zipkin:
    base-url: http://${ip}:9411/
    discoveryClientEnabled: false
  sleuth:
    sampler:
      # 抽样率，默认是0.1（10%）
      probability: 1.0
server:
  port: 9100

feign:
  client:
    config:
      # 通过 default 进行全局配置
      default:
        loggerLevel: full
        connectTimeout: 10000
        readTimeout: 10000
  httpclient:
    enabled: true
    max-connections: 200
    max-connections-per-route: 50
logging:
  config: classpath:log4j2-test.xml

studyUrl: https://dev.center.duizhang100.cn
# 公众号配置信息
gongzhonghao:
  appId: wx876660e0c4b48729
  secret: 99c6d530ec67582061c731b43e6a2448
  redirect:
    # 微信授权结束后跳转的路径
    partner: ${studyUrl}/partner

qywx:
  appId: wwe6e0ef9e01f6d6aa
  secret: pxf5D_K3F9jFPwRTksCRXERkar3rOdOLmyYfImmv11o
  # 授权链接
  authLink: https://open.weixin.qq.com/connect/oauth2/authorize?appid=${qywx.appId}&redirect_uri=${qywx.redirect.redirect_uri}&response_type=code&scope=snsapi_base&state=STATE#wechat_redirect
  redirect:
    # 企业微信登录地址
    login: ${studyUrl}/center/wechat/qy/login
    # 授权后重定向的回调链接地址
    redirect_uri: ${studyUrl}/center/wechat/qy/auth/auth

