spring:
  application:
    name: spring-boot-admin
  cloud:
    nacos:
      discovery:
        server-addr: nacos.duizhang100.cn:8848
        # 生产环境
        namespace: 98b133ab-9b67-4919-adb4-e8a1c96db7cf
        #开发环境
#        namespace: a8dd697b-5d6d-4844-bcc7-54a7732644e8
#        group: wuchenxi
server:
  port: 8849
